Traceback (most recent call last):
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import display
import pandas as pd

data = pd.read_csv('tables\key_actors.csv', index_col=False).style.hide_index()

display(data)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_21996\3496323807.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mfrom[0m [0mIPython[0m[1;33m.[0m[0mdisplay[0m [1;32mimport[0m [0mdisplay[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [0mdata[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'tables\key_actors.csv'[0m[1;33m,[0m [0mindex_col[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m.[0m[0mstyle[0m[1;33m.[0m[0mhide_index[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

