Traceback (most recent call last):
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 708, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\TMillaKoch\Anaconda3\envs\test\lib\site-packages\nbclient\client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

import pandas as pd
import warnings

warnings.filterwarnings('ignore')


data = pd.read_csv('tables\key_actors.csv', index_col=False).style.hide_index()

data.style.hide_index().set_properties(**{'text-align': 'left'})
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_19864\451050453.py[0m in [0;36m<module>[1;34m[0m
[0;32m      7[0m [0mdata[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'tables\key_actors.csv'[0m[1;33m,[0m [0mindex_col[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m.[0m[0mstyle[0m[1;33m.[0m[0mhide_index[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [1;33m[0m[0m
[1;32m----> 9[1;33m [0mdata[0m[1;33m.[0m[0mstyle[0m[1;33m.[0m[0mhide_index[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mset_properties[0m[1;33m([0m[1;33m**[0m[1;33m{[0m[1;34m'text-align'[0m[1;33m:[0m [1;34m'left'[0m[1;33m}[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mAttributeError[0m: 'Styler' object has no attribute 'style'
AttributeError: 'Styler' object has no attribute 'style'

